name: Supabase Keep Alive

on:
  schedule:
    - cron: '0 0 */3 * *' # Se ejecuta cada 3 días
  workflow_dispatch: # Permite ejecución manual

jobs:
  ping_db:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase Database
        env:
          SUPABASE_DB_URL: ${{ secrets.SUPABASE_DB_URL }}
        run: |
          psql "$SUPABASE_DB_URL" -c "SELECT 1;"
